const PlaceTypesUkrainian = {
    wedding_venue: "Місце для весілля",
    banquet_hall: "Банкетний зал",
    restaurant: "Ресторан",
    cafe: "Кафе",
    bar: "Бар",
    community_center: "Громадський центр",
    park: "Парк",
    event_venue: "Місце для подій",
    convention_center: "Конференц-центр",
    hotel: "Готель", 
    state_park: "Державний парк",
    national_park: "Національний парк",
    historical_landmark: "Історична пам'ятка",
    plaza: "Площа",
    concert_hall: "Концертний зал",
    museum: "Музей", 
    amusement_park: "Парк розваг",
    tourist_attraction: "Туристична визначна пам'ятка",
    cultural_center: "Культурний центр",
    garden: "Сад",
    amphitheatre: "Амфітеатр",
    zoo: "Зоопарк",
    american_restaurant: "Американський ресторан",
    italian_restaurant: "Італійський ресторан",
    mexican_restaurant: "Мексиканський ресторан",
    japanese_restaurant: "Японський ресторан",
    chinese_restaurant: "Китайський ресторан",
    seafood_restaurant: "Ресторан морепродуктів",
    steak_house: "Стейк-хаус",
    pizza_restaurant: "Піцерія",
    sushi_restaurant: "Суші-ресторан",
    fast_food_restaurant: "Ресторан швидкого харчування",
    meal_delivery: "Доставка їжі",
    meal_takeaway: "Їжа на винос",
    brunch_restaurant: "Ресторан для бранчу",
    breakfast_restaurant: "Ресторан для сніданку",
    bakery: "Пекарня",
    dessert_restaurant: "Ресторан десертів",
    ice_cream_shop: "Магазин морозива",
    candy_store: "Магазин солодощів",
    chocolate_shop: "Магазин шоколаду",
    coffee_shop: "Кав'ярня",
    tea_house: "Чайний дім",
    wine_bar: "Винний бар",
    pub: "Паб",
    adventure_sports_center: "Центр пригодницького спорту",
    amusement_center: "Центр розваг",
    aquarium: "Акваріум",
    barbecue_area: "Майданчик для барбекю",
    botanical_garden: "Ботанічний сад",
    bowling_alley: "Боулінг",
    childrens_camp: "Дитячий табір",
    comedy_club: "Комедійний клуб",
    cycling_park: "Велосипедний парк",
    dance_hall: "Танцювальний зал",
    dog_park: "Собачий парк",
    ferris_wheel: "Оглядове колесо",
    hiking_area: "Місцевість для пішого туризму",
    internet_cafe: "Інтернет-кафе",
    karaoke: "Караоке",
    marina: "Пристань",
    movie_rental: "Прокат фільмів",
    movie_theater: "Кінотеатр",
    night_club: "Нічний клуб",
    observation_deck: "Оглядовий майданчик",
    off_roading_area: "Місцевість для бездоріжжя",
    opera_house: "Оперний театр",
    philharmonic_hall: "Філармонійний зал",
    picnic_ground: "Місце для пікніка",
    planetarium: "Планетарій",
    roller_coaster: "Американські гірки",
    skateboard_park: "Скейт-парк",
    video_arcade: "Відеоаркада",
    visitor_center: "Інформаційний центр",
    water_park: "Аквапарк",
    wildlife_park: "Парк дикої природи",
    wildlife_refuge: "Заповідник дикої природи",
    afghani_restaurant: "Афганський ресторан",
    african_restaurant: "Африканський ресторан",
    asian_restaurant: "Азіатський ресторан",
    bagel_shop: "Магазин бубликів",
    bar_and_grill: "Бар і гриль",
    barbecue_restaurant: "Ресторан барбекю",
    brazilian_restaurant: "Бразильський ресторан",
    buffet_restaurant: "Ресторан-буфет",
    cafeteria: "Кафетерій",
    cat_cafe: "Котяче кафе",
    chocolate_factory: "Шоколадна фабрика",
    confectionery: "Кондитерська",
    deli: "Гастроном",
    diner: "Закусочна",
    dog_cafe: "Собаче кафе",
    donut_shop: "Магазин пончиків",
    fine_dining_restaurant: "Ресторан високої кухні",
    food_court: "Фуд-корт",
    french_restaurant: "Французький ресторан",
    greek_restaurant: "Грецький ресторан",
    hamburger_restaurant: "Ресторан гамбургерів",
    indian_restaurant: "Індійський ресторан",
    indonesian_restaurant: "Індонезійський ресторан",
    lebanese_restaurant: "Ліванський ресторан",
    mediterranean_restaurant: "Середземноморський ресторан",
    middle_eastern_restaurant: "Близькосхідний ресторан",
    ramen_restaurant: "Рамен-ресторан",
    sandwich_shop: "Сендвіч-шоп",
    spanish_restaurant: "Іспанський ресторан",
    thai_restaurant: "Тайський ресторан",
    turkish_restaurant: "Турецький ресторан",
    vegan_restaurant: "Веганський ресторан",
    vegetarian_restaurant: "Вегетаріанський ресторан",
    vietnamese_restaurant: "В'єтнамський ресторан"
  };
  
  export { PlaceTypesUkrainian };